apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ldap-config
  namespace: monitoring
data:
  ldap.toml: |
    [[servers]]
    host = "openldap.ldap.svc.cluster.local"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = true

    # Usuario con permisos para hacer búsquedas
    bind_dn = "cn=admin,dc=example,dc=org"
    bind_password = "adminpassword"  # ⚠️ Para producción, mejor usar un Secret + initContainer

    # Cómo buscar el usuario en LDAP
    search_filter = "(uid=%s)"
    search_base_dns = ["ou=users,dc=example,dc=org"]

    [servers.attributes]
    name = "givenName"
    surname = "sn"
    username = "uid"
    email = "mail"
