apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: openldap.ldap.svc.cluster.local
            - name: PHPLDAPADMIN_LDAP_PORT
              value: "389"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
            - name: PHPLDAPADMIN_TRUST_PROXY
              value: "true"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  selector:
    app: phpldapadmin
  ports:
    - port: 80
      targetPort: 80
