apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [security]
    admin_user = admin
    admin_password = admin123

    [auth.anonymous]
    enabled = false

    [server]
    root_url = http://localhost:3000
