replicas: 1
minimumMasterNodes: 1

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false

secret:
  enabled: true
  password: "0c0duBmBLvvJw5o2"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
