filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log

    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      username: ""
      password: ""
      protocol: "http"

    setup.kibana:
      host: "http://kibana-kibana:5601"
      protocol: "http"

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
