service:
  type: NodePort

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "http://localhost:5601"
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    xpack.security.enabled: false
