apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aplicacion-tls
  namespace: aplicacion
spec:
  secretName: aplicacion-tls-secret
  duration: 2160h       # 90 días
  renewBefore: 360h     # 15 días antes
  commonName: aplicacion.local
  dnsNames:
    - aplicacion.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
