apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls-secret
  duration: 2160h       # 90 días
  renewBefore: 360h     # 15 días antes
  commonName: prometheus.monitor.local
  dnsNames:
    - prometheus.monitor.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
