{
 "title": "Logs aplicacion",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/containers/aplicacion-6b7695b7d4-dwjfq_aplicacion_flask-1a2939e7126aeada2426e1e286eca39ada7608bbc3d99ddce96689718de73331.log\"} \r\n|~ \"❌ Tarea eliminada\"\r\n"
    }
   ]
  },
  {
   "title": "Tareas eliminadas 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/containers/aplicacion-6b7695b7d4-dwjfq_aplicacion_flask-1a2939e7126aeada2426e1e286eca39ada7608bbc3d99ddce96689718de73331.log\"} \r\n|~ \"❌ Tarea eliminada \" [24h])"
    }
   ]
  },
  {
   "title": "Alta de tareas",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/containers/aplicacion-6b7695b7d4-dwjfq_aplicacion_flask-1a2939e7126aeada2426e1e286eca39ada7608bbc3d99ddce96689718de73331.log\"} \r\n|~ \"✔ Tarea agregada\""
    }
   ]
  },
  {
   "title": "Tareas creadas 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/containers/aplicacion-6b7695b7d4-dwjfq_aplicacion_flask-1a2939e7126aeada2426e1e286eca39ada7608bbc3d99ddce96689718de73331.log\"} \r\n|~ \"✔ Tarea agregada\" [24h])\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/containers/aplicacion-6b7695b7d4-dwjfq_aplicacion_flask-1a2939e7126aeada2426e1e286eca39ada7608bbc3d99ddce96689718de73331.log\"} \r\n!= \"\\\"GET /tareas HTTP/1.1\\\" 200 -\"\r\n!= \"📄 Página principal cargada\"\r\n!= \"GET /static/styles.css HTTP/1.1\""
    }
   ]
  }
 ]
}