{
 "title": "Logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Tarea Añadidas",
   "type": "logs",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{pod=~\"aplicacion-6b7695b7d4-.*\"} |= \"Tarea agregada\""
    }
   ]
  },
  {
   "title": "Contador tareas añadidas (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"aplicacion-6b7695b7d4-.*\"} |= \"Tarea agregada\" [24h])"
    }
   ]
  },
  {
   "title": "Log Tarea Eliminada",
   "type": "logs",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{pod=~\"aplicacion-6b7695b7d4-.*\"} |= \"Tarea eliminada\""
    }
   ]
  },
  {
   "title": "Contador tareas borradas(24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"aplicacion-6b7695b7d4-.*\"} |= \"Tarea eliminada\" [24h])"
    }
   ]
  },
  {
   "title": "Logs Aplicacion (TODOS)",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{pod=~\"aplicacion-6b7695b7d4-.*\"} |= \"\""
    }
   ]
  }
 ]
}