apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls-secret
  duration: 2160h       # 90 días
  renewBefore: 360h     # 15 días antes
  commonName: grafana.monitor.local
  dnsNames:
    - grafana.monitor.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
