admin:
  existingSecret: grafana-admin-secret  # Usar Secret en lugar de adminPassword en texto plano

persistence:
  enabled: true
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local
