loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_retain_period: 30s
      wal:
        enabled: true

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    limits_config:
      retention_period: 168h

    chunk_store_config:
      max_look_back_period: 0s

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: do-block-storage

service:
  type: ClusterIP
